<?php

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Joli\Jane\OpenApi\Tests\Expected\Model;

class Schema
{
    /**
     * @var SchemaObjectProperty
     */
    protected $objectProperty;
    /**
     * @var SchemaObjectPropertyMulti
     */
    protected $objectPropertyMulti;
    /**
     * @var Schema
     */
    protected $objectRefProperty;

    /**
     * @return SchemaObjectProperty
     */
    public function getObjectProperty()
    {
        return $this->objectProperty;
    }

    /**
     * @param SchemaObjectProperty $objectProperty
     *
     * @return self
     */
    public function setObjectProperty(SchemaObjectProperty $objectProperty = null)
    {
        $this->objectProperty = $objectProperty;

        return $this;
    }

    /**
     * @return SchemaObjectPropertyMulti
     */
    public function getObjectPropertyMulti()
    {
        return $this->objectPropertyMulti;
    }

    /**
     * @param SchemaObjectPropertyMulti $objectPropertyMulti
     *
     * @return self
     */
    public function setObjectPropertyMulti(SchemaObjectPropertyMulti $objectPropertyMulti = null)
    {
        $this->objectPropertyMulti = $objectPropertyMulti;

        return $this;
    }

    /**
     * @return Schema
     */
    public function getObjectRefProperty()
    {
        return $this->objectRefProperty;
    }

    /**
     * @param Schema $objectRefProperty
     *
     * @return self
     */
    public function setObjectRefProperty(self $objectRefProperty = null)
    {
        $this->objectRefProperty = $objectRefProperty;

        return $this;
    }
}
